services:
  - type: web
    name: urlx
    env: go
    buildCommand: go build -o urlx main.go
    startCommand: ./urlx
    plan: free
    envVars:
      - fromEnvGroup: urlx-db-env
    databases:
      - name: urlx-db
        plan: free
        databaseName: urlx
        user: urlx_user
